services:
    mysql:
        image: mysql/mysql-server:8.0
        container_name: rbac_mysql
        hostname: mysql
        volumes:
            - "./data:/docker-entrypoint-initdb.d/"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=rbac
            - MYSQL_USER=reinmind
            - MYSQL_PASSWORD=K5bernetes
            - LANG=en_US.UTF-8
            - MYSQL_ROOT_PASSWD=K5bernetes
    app:
        image: openjdk:8
        container_name: rbac_app
        hostname: app
        volumes:
            - "./target:/data"
        ports:
            - "8081:8081"
        entrypoint: ["java","-jar","/data/spring-rbac-1.0.jar"]
