server:
  port: 8081
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1db5ttsxnkk51p1vo.mysql.rds.aliyuncs.com:3306/rbac
    username: reinmind
    password: K5bernetes
